services:
    web:
        build: .
        volumes:
        - .:/var/www/html
        env_file:
        - .env
        environment:
          - DB_HOST=shared-mysql
        restart: unless-stopped
        ports:
        - "${TRADING_PORT}:80"
        networks:
            - internal
            - shared-laravel-network
volumes:
    db_data:

networks:
    internal:
        driver: bridge
    shared-laravel-network:
        external: true
  